language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_install: "cd nodejs"
script: make test 
branches:
  only:
    - master
    - testing
env:
  - secure: "cs22x/kFdKmpgPCLYYkhsZJM/NqR/mTWiTzjj9mQTPdOp5SsPUPaFYY/b3HMBTyNXxx2tVc2E7jlOHKMl5Dp4uku8pnn0s8Imoktnf7PuYrN75OmybPw2nWH+UBc+umfb/ZhJ5kewW+Ok2DuI2OrS0s0bdFljbAOKhsVLTkcf4Q="
  - secure: "RXAvz/G8tgLaq6BqOXuZ0WRZ2qx3oIW0TYp8GwhDHpq7JdAwLRYy0zRODCfvvX+zDyAYzIg5w481S637Bn4lDG7RpxLsM8M84Py9SBpO1hxnHGdSVNwt3nB6/8sXwa5hwxkw3WaP0WcZb58N3B/JeG7N5k4gULoN6JNOhhAPX+Y="
