language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_install: "cd nodejs"
script: make test 
branches:
  only:
    - master
    - testing
env:
  - secure: "cs22x/kFdKmpgPCLYYkhsZJM/NqR/mTWiTzjj9mQTPdOp5SsPUPaFYY/b3HMBTyNXxx2tVc2E7jlOHKMl5Dp4uku8pnn0s8Imoktnf7PuYrN75OmybPw2nWH+UBc+umfb/ZhJ5kewW+Ok2DuI2OrS0s0bdFljbAOKhsVLTkcf4Q="
  - secure: "WvGJqmk+F+apU2P8TpK9VDOOtFdKyK82edQIsJtC8W8tMIzwRwoNM6MnRJjlSyAAgNCPiKKy719/JPS6LYSfitt+rf1O53QwQIQsksT+asf46ie0+uNtCs9ObbQs1Wlb467c9pc+Ul8SvILEIAUKSTcT08ZWEqfk4xYZgeFM/uE="
