language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_install: "cd nodejs"
script: make test 
branches:
  only:
    - master
    - testing
env:
  global: 
    - secure: "cs22x/kFdKmpgPCLYYkhsZJM/NqR/mTWiTzjj9mQTPdOp5SsPUPaFYY/b3HMBTyNXxx2tVc2E7jlOHKMl5Dp4uku8pnn0s8Imoktnf7PuYrN75OmybPw2nWH+UBc+umfb/ZhJ5kewW+Ok2DuI2OrS0s0bdFljbAOKhsVLTkcf4Q="
    - secure: "RxX/TUsIj1nUXGmTdYnp4gOWJ1B4ionHpyygasMXsvtEEi+bs7HDJtuSKEZcsfoMwrjjfsMOZpR0/C+gqAaCJFXs4asosu90ueWvw5yuXGOcBKWt9PZQQ8F6pZQnkfnGMPwrv0tLJSTrT/wEcFjOfFNDPMv2Io3w5x1PXctJb5k=" 
