language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_install: "cd nodejs"
script: make test 
branches:
  only:
    - master
    - testing
env:
  global: 
    - secure: "cs22x/kFdKmpgPCLYYkhsZJM/NqR/mTWiTzjj9mQTPdOp5SsPUPaFYY/b3HMBTyNXxx2tVc2E7jlOHKMl5Dp4uku8pnn0s8Imoktnf7PuYrN75OmybPw2nWH+UBc+umfb/ZhJ5kewW+Ok2DuI2OrS0s0bdFljbAOKhsVLTkcf4Q="
    - secure: "JGEL9m6/6ktCHErWG6DfrSUqawUPwNwpD1favjgLx4r+tpVGztquqHb6donSjQhaScrA7XoBtfDiht4mWZrSAOJOC7/FceJCBWusbMobdznPaU8rOjdr1BKZIZVsvhhFG6znIw1fvpjKpkEK/e77nwU/spK8GYv3wJbLb6GKjdY="  
