language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_install: "cd nodejs"
before_script:
  - npm install -g mocha
  - npm install chai
script: mocha
branches:
  only:
    - testing
